apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-deployment
  labels:
    app: home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home
  template:
    metadata:
      labels:
        app: home
    spec:
      containers:
      - name: home
        image: 148014383077.dkr.ecr.us-east-1.amazonaws.com/shopping-site-home:eadaba8949b9b675666b1ecc34e09eb90f4d2d8f
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: home-service
  labels:
    app: home
spec:
  type: ClusterIP
  selector:
    app: home
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
