apiVersion: apps/v1
kind: Deployment
metadata:
  name: two-wheelers-deployment
  labels:
    app: two-wheelers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: two-wheelers
  template:
    metadata:
      labels:
        app: two-wheelers
    spec:
      containers:
      - name: two-wheelers
        image: 148014383077.dkr.ecr.us-east-1.amazonaws.com/shopping-site-two-wheelers:27e26f0aaee7a3742ef76d323f73ce1e3ceb2aaa
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: two-wheelers-service
  labels:
    app: two-wheelers
spec:
  type: ClusterIP
  selector:
    app: two-wheelers
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
